[build]
    command = "npm run build"
    publish = "/dist/public"

[context.production]
    environment = { NODE_VERSION = "14.16.1" }

[[redirects]]
    from = "/*"
    to = "/public"
    status = 200
