[build]
    command = "npm run build"
    base = "/"
    publish = "/dist"

[context.production]
    environment = { NODE_VERSION = "14.16.1" }

[[redirects]]
    from = "/*"
    to = "/dist"
    status = 200
