[build]
    command = "npm run build"
    publish = "/dist"
    base = "/"

[context.production]
    environment = { NODE_VERSION = "14.16.1" }

[[redirects]]
    from = "/*"
    to = "/public/index.html"
    status = 200
